### ISSUE TITLE
添加App卸载功能

### ISSUE THREAD

**Issue by Mustenaka** [liangxiegame/QFramework#115]
在工业Unity项目需求中，QF可以很好的辅助数据流、事件的处理并且自带一套MVC，而工业项目中往往需要设计多个完全不同的系统去处理，实际会出现使用多个QF框架的情况。为了便于管理进行编写管理控制类统一维护处理，因此需要请求更新新增，卸载QF框架的功能。

**Comment by liangxiegame** [comment]
好的 谢谢反馈 我会尽快支持

**Comment by Mustenaka** [comment]
谢谢凉鞋

**Comment by liangxiegame** [comment]
已经增加 Deinit 方法

**Comment by Mustenaka** [comment]
谢谢，这就去更新
