### ISSUE TITLE
导入8.FlappyBird.Unity2019.4+的包,出现报错Argument 1: cannot convert from 'QFramework.BindableProperty<int>' to 'int',使用unity2021.3.16f1c

### ISSUE THREAD

**Issue by plmkojx** [liangxiegame/QFramework#131]
导入8.FlappyBird.Unity2019.4+的包,出现报错Argument 1: cannot convert from 'QFramework.BindableProperty<int>' to 'int',使用unity2021.3.16f1c1

![企业微信截图_2024031118391411111111111111111](https://github.com/liangxiegame/QFramework/assets/5427557/732f9174-cf99-4f4f-8840-ef82662c5617)

**Comment by liangxiegame** [comment]
好的 先调用下 .Value 我后边改完会更新 感谢反馈







| |
凉鞋
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年3月11日 18:41 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [liangxiegame/QFramework] 导入8.FlappyBird.Unity2019.4+的包,出现报错Argument 1: cannot convert from 'QFramework.BindableProperty<int>' to 'int',使用unity2021.3.16f1c (Issue #131) |

导入8.FlappyBird.Unity2019.4+的包,出现报错Argument 1: cannot convert from 'QFramework.BindableProperty' to 'int',使用unity2021.3.16f1c1

_2024031118391411111111111111111.png (view on web)

**Comment by plmkojx** [comment]
好的 谢谢

![image](https://github.com/liangxiegame/QFramework/assets/5427557/cbacd7be-cc29-4bf8-ab6b-87f13196b0f0)
还个问题 这个扩展方法单独写出来为了让继承IUnRegister的类初始时实现少量的方法,扩展方法按需再设置还是为了兼容老版本(兼容老版本的话 新人接触看的好晕,能出个正式版更好和兼容版区分开)

**Comment by liangxiegame** [comment]
这个是为了区分 Godot 还是 Unity
