### ISSUE TITLE
EasyGrid<T>无法对外提供get方法

### ISSUE THREAD

**Issue by EmperorQ** [liangxiegame/QFramework#140]
liangxie老师您好，问一个比较基础的问题
```
private EasyGrid<SoilData> mShowGrid = new EasyGrid<SoilData>(10, 10);
public EasyGrid<SoilData> ShowGrid => mShowGrid;
```
`ShowGrid`提示属性类型`EasyGrid<SoilData>`的可访问性低于属性`GridControler.ShowGrid`
![image](https://github.com/user-attachments/assets/4d04082c-c679-496b-9fe1-3afeffe8cf9a)

希望能够解答一下，不胜感激！

**Comment by liangxiegame** [comment]
您好，请加一下课程交流群，否则无法判断您的教程来源。

**Comment by EmperorQ** [comment]
> 您好，请加一下课程交流群，否则无法判断您的教程来源。

b站上的，已加群

**Comment by EmperorQ** [comment]
SoilData声明成public就OK了
