### ISSUE TITLE
`System.Console' does not contain a definition for `ReadKey'

### ISSUE THREAD

**Issue by kpkhxlgy0** [liangxiegame/QFramework#17]
我使用的是Unity3D2017.3.0

**Comment by liangxieq** [comment]
![2018-02-08 18 36 24](https://user-images.githubusercontent.com/24365011/35968497-007378e6-0cff-11e8-845e-e4ff321bc80a.png)

麻烦 Api Compatibility Level 选择 .Net 2.0
