### ISSUE TITLE
接收事件参数，中文会产生字符串乱码的问题。

### ISSUE THREAD

**Issue by zzjfengqing** [liangxiegame/QFramework#2]
void Update()
    {
        this.SendGlobalMsg("Receiver Show Sth", "你好", "世界");
    }

 void ReceiverMsg(params object[] paramList)
    {
        foreach (var sth in paramList)
        {
            Debug.Log(sth);
        }
    }

接收中文参数，但是Debug输出的中文是一堆乱码。 Unity5.4f3版本。

**Comment by liangxiegame** [comment]
好 谢谢提醒 我会尽快修复

**Comment by zzjfengqing** [comment]
非常不好意思。。。是我的编辑器字符编码错误的问题。。。。跟您的框架没啥问题。。。实在不好意思。。。
