### ISSUE TITLE
Add Example about GUI system?

### ISSUE THREAD

**Issue by takaaptech** [liangxiegame/QFramework#20]
Please add simple example how to create main menu, setting window and play window using GUI system please!
Thank so much!

**Comment by liangxieq** [comment]
@takaaptech hi,I'll add it tomorrow,thx for your issue.

**Comment by takaaptech** [comment]
Hi!
Thank so much!

**Comment by liangxieq** [comment]
@takaaptech  welcome! Wish u create more issue 2 improve qframework
