### ISSUE TITLE
1.DataStructure中的Array类中的RemoveAt方法是有问题

### ISSUE THREAD

**Issue by woopqww111** [liangxiegame/QFramework#21]
![image](https://user-images.githubusercontent.com/11883094/37754626-42d13d00-2ddd-11e8-8c85-d7073356c88d.png)

**Comment by liangxieq** [comment]
好谢谢 我查一下问题

**Comment by karsion** [comment]
newIndex初始化应该 = index，但newIndex可以不用，数据迁移应该是for (i = index; i < size;) array[i] = array[++i]
