### ISSUE TITLE
Maybe bug in Cache of UIPanel

### ISSUE THREAD

**Issue by takaaptech** [liangxiegame/QFramework#22]
Hi!
I just open 1.Example scene and press Setting button to show UISettingPanel and back.
Every time i do that, Instantiate call in QUIBehaviour (Line 61)

		public static QUIBehaviour Load(string panelName, string assetBundleName = null)
		{
			var panelLoader = new DefaultUIPanelLoader();
			var panelPrefab = assetBundleName.IsNullOrEmpty()
				? panelLoader.LoadPanelPrefab(panelName)
				: panelLoader.LoadPanelPrefab(assetBundleName, panelName);
			var obj = Instantiate(panelPrefab);
			Debug.LogWarning("Instantiate " + panelName);
			var retScript = obj.GetComponent<QUIBehaviour>();
			retScript.mUiPanelLoader = panelLoader;
			return retScript;
		}

Please check!
![screen shot 2018-03-26 at 9 20 13 am](https://user-images.githubusercontent.com/6276251/37883849-1d4e733e-30d7-11e8-8ed6-82567bd8d108.png)

**Comment by liangxieq** [comment]
hi thx! we'll check it right now

**Comment by liangxieq** [comment]
hi,Cache Feature of uipanel is not support yet,so sorry!
but we'll support it next version.

| UIMgr | GameObject | UIBehaviour |
|-- | -- | --|
| UIMgr.OpenPanel | Load&Instantiate | UIPanel.Init&RegisterEvent |
| UIMgr.Show | gameObject.SetActive(true) | UIPanel.OnShow |
| UIMgr.Hide | gameObject.SetActive(false) | UIPanel.OnHide |
| UIMgr.ClosePanel | gameObject.Destroy & Unload prefab | UIPanel.OnClose |

above is relation of UIMgr,GameObject and UIBehaviour

**Comment by liangxieq** [comment]
the cache of panel's prefab are supported by ResLoader & ResMgr

**Comment by takaaptech** [comment]
@liangxieq 
In UIPanel, each time I press the Setting button, the code still Instantiate new game object by Prefab.
Can you explain how to cache by ResLoader & ResMgr? 
Thank so much!

		public static UIPanel Load(string panelName, string assetBundleName = null)
		{
			var panelLoader = new DefaultUIPanelLoader();
			var panelPrefab = assetBundleName.IsNullOrEmpty()
				? panelLoader.LoadPanelPrefab(panelName)
				: panelLoader.LoadPanelPrefab(assetBundleName, panelName);
			var obj = Instantiate(panelPrefab);
			Debug.LogWarning("Instantiate " + panelName);
			var retScript = obj.GetComponent<UIPanel>();
			retScript.mUiPanelLoader = panelLoader;
			return retScript;
		}
