### ISSUE TITLE
Unity版本还是5.0以前的吗

### ISSUE THREAD

**Issue by Deepslient** [liangxiegame/QFramework#24]
Unity版本还是5.0以前的吗。。。

**Comment by liangxieq** [comment]
@Deepslient 不是的，支持到 Unity 5.x ~ 2017.x，您有 5.0 之前的需求嘛?

**Comment by Deepslient** [comment]
不是呢，我5.4导入提示版本是before5.0的

**Comment by Deepslient** [comment]
并且报这个错：Assets/QFramework/Framework/0.Libs/0.Extension/1.DotNet/IO.cs(438,40): error CS0121: The call is ambiguous between the following methods or properties: `QFramework.IOExtension.GetFileName(string, char)' and `QFramework.IOExtension.GetFileName(this string)'，刚刚才下载的

**Comment by liangxieq** [comment]
@Deepslient  打错了 是 5.5  ~ 2017.x ...

**Comment by liangxieq** [comment]
@Deepslient 是 git clone 的嘛？

**Comment by Deepslient** [comment]
是滴，那我用5.6试试先，我又重新下载了一次，提示最近更新2天前

**Comment by liangxieq** [comment]
@Deepslient  嗯嗯，不好意思啊。 您试下，如果还不行，进下 QQ 群:623597263，这里人多力量大，问题好解决，哈哈哈。

**Comment by Deepslient** [comment]
已经进了，感谢你们的无私才对，谢谢你们

**Comment by liangxieq** [comment]
@Deepslient 谢谢支持,issue 关掉啦~
