### ISSUE TITLE
Error when switch platform to android and build

### ISSUE THREAD

**Issue by takaaptech** [liangxiegame/QFramework#26]
Hi!
Please check if we trying to build android apk

![screen shot 2018-05-28 at 10 34 25 am](https://user-images.githubusercontent.com/6276251/40596090-cf6d1a86-6262-11e8-96a5-59ca865a3bb2.png)
Thank so much!

**Comment by liangxieq** [comment]
@takaaptech thx for this issue. we fix the compile errors.
