### ISSUE TITLE
ResizableArray

### ISSUE THREAD

**Issue by better666** [liangxiegame/QFramework#27]
这个里面修改长度，直接用Array.Resize ，每次添加或者移除都会调用，这样会产生较高的GC。很多情况还不如List好一点。

**Comment by liangxieq** [comment]
@better666 谢谢建议。

**Comment by liangxieq** [comment]
List 内部也是调用了 Array.Resize 这个接口，虽然说 List 造成 GC 的频率可能没有 Array.Resize 这么高，但是每次开辟的内存都是翻倍的。ResizableArray 虽然说每次增加或者减少都会造成 GC，不过 Array.Resize 的范围是可控的。 

当初设计 ResizableArray 是为了支持  QFramework 里的 UpdateMgr,这里需要缓存非常多的基类，这个基类的数字大部分情况下是固定的。这个更利于去管理数量比较多的对象。而有 Update 回调基类大部分也是固定的，就算不固定的，数量非常多的时候都会缓存到对象池里，并不会真正意义上进行销毁。

后来 UpdateMgr 雪藏了，之后会公布出来，估计 0.0.4 左右的版本能找到这个类。

总之问题问得非常不错。
