### ISSUE TITLE
ActionKit.FSM

### ISSUE THREAD

**Issue by better666** [liangxiegame/QFramework#29]
1、不知道是否FSMLite时FSM的轻量版，这两个有点重复
2、从HandleEvent方法看，目标状态必须与当前状态建立连接，也就是无法强制跳转至某个状态。从当前状态切换至任意状态，作为基础功能应该要放开的
3、FSMState中可以加一个Update，Reset方法，这样让状态又更多功能

**Comment by liangxieq** [comment]
1. FSMLite 是基于表的状态机，这里的状态和跳转是必须限制的。
2.同上。
3.类似的功能其实在 NodeSystem 里有实现。
