### ISSUE TITLE
节点更新代码

### ISSUE THREAD

**Issue by better666** [liangxiegame/QFramework#31]
对于类似delay，以及其他容器节点起更新都是用协程处理的。个人建议要么用计时器或者在一个一直处于激活状态的脚本中启动协程。这样避免物体被隐藏或者删除在成协程意外中止，引起不可预知的错误。也可以增加时间缩放功能（比如定时更服务器刷状态，但此时又设置了timeSacle）

**Comment by liangxieq** [comment]
启动节点的方式有两种建议查看下文档，http://qframework.io/Assets/QFramework/Framework/1.ActionKit/Document.html

一种是 MonoBehaviour 触发，底层原理是 MonoBehaivour 启动的协程，来刷执行节点，这样做的原因是生命周期由 MonoBehaviour 控制。

另一种就是用线程或者任意 MonoBehaivour 的Update 去刷执行节点。

第一种也可以使用 QUIManager.Instance.Delay(); 这种方式去触发的。
