### ISSUE TITLE
Tutorial in english about Asset Bundle

### ISSUE THREAD

**Issue by takaaptech** [liangxiegame/QFramework#35]
Hi!
Could you please write some tutorial or take some simple note in English how to use Asset Bundle when we build the game on android and ios? For example how we use assets bundle in our UIKit example instead of using prefab
Thank so much!

**Comment by liangxieq** [comment]
OK, I'll do this before tomorrow.

**Comment by takaaptech** [comment]
@liangxiegame Please update link here if you have done for the tutorial!
Thank so much!

**Comment by liangxieq** [comment]
UI Kit example already support the Res Kit.
Res Kit usage is very simple.
In simulation mode you just right click the folder/asset .the folder/asset is become asset bundle without ab build.

in non smulation mode, you need  calll ResMgr.Init() once in game launch and build the assetbundle everytime you modified assets.

The quick short command of open ResKit setting window  is  "Cmd/Ctrl + Shift +r".

in ResKit Setting window you can config the  simulation mode and build the assetbundle

sorry for this late reply.

**Comment by liangxieq** [comment]
Just drag UISectionPanel 2 non Resources folder,and mark as AssetBundle.
then change above code 2 
``` csharp
UIMgr.OpenPanel<UISectionPanel>(UILevel.Common);
```
or
``` csharp
UIMgr.OpenPanel(UILevel.Common,prefabName:"UISectionPanel");
```

**Comment by liangxieq** [comment]
please make sure call ResMgr.Init() once when Game Start.

**Comment by takaaptech** [comment]
I call ResMgr.Init(); and it works like a charm!
Thankyou @liangxieq 
P/S
I forgot to call it because From the comment above you mention only call it in non-simulation mode?

in non smulation mode, you need calll ResMgr.Init() once in game launch and build the assetbundle everytime you modified assets.

**Comment by liangxieq** [comment]
haha sorry for misleading .

**Comment by takaaptech** [comment]
Thank @liangxieq
I just build and run apk on Xiaomi Remi note 4x and UISectionPanel seems weird!
I think I can capture the image and send apk for you in case you want to check something!
https://drive.google.com/file/d/16er5vRqnLSjRTyTZE61nC6QbNNOmnOeo/view?usp=sharing

![1535428213009](https://user-images.githubusercontent.com/6276251/44699861-63323180-aab0-11e8-8fcc-a46c17df6203.JPEG)

**Comment by liangxieq** [comment]
thx， the ui kit example is not test for device yet. i'll test it in weeks. thx for your feedback.

**Comment by liangxieq** [comment]
You may do more feedback about QFramework, it's ready help us to improvement this product.
