### ISSUE TITLE
直接导入0.0.8的demo有大量报错？

### ISSUE THREAD

**Issue by ilvxna** [liangxiegame/QFramework#36]
如下图所示：

![1](https://user-images.githubusercontent.com/6600828/44628214-17776f00-a96e-11e8-9080-4e1ad8461e7a.JPG)

**Comment by liangxieq** [comment]
qframework 版本是多少？

**Comment by liangxieq** [comment]
现在 Demo 版本 已经是 v0.0.10 来，下载最新版 QFramework 快捷键 Cmd/Ctrl + e 就能看到下载。
