### ISSUE TITLE
Is UI Kit support transition effect between panels?

### ISSUE THREAD

**Issue by takaaptech** [liangxiegame/QFramework#37]
Hi!
I want to transition between panels more smooth by Fade-in and Fade-out some components
For example from the menu to game panel, When user press play button, I want tween Fade-out menu 0.5 s and then Fade-in game panel in 0.5 s
So is this support yet or how can we do this?
Thank so much!

**Comment by liangxieq** [comment]
it's not support, but this feature must support.  may be this week. can you wait for this?

**Comment by takaaptech** [comment]
That is awesome! I can wait. I will ping you on the weekend in case you have many things to do.
Thank so much @liangxieq !

**Comment by liangxieq** [comment]
haha!  thx for your kindness.

**Comment by takaaptech** [comment]
Hi @liangxieq 
I will try it now, thank so much for your support!

**Comment by liangxieq** [comment]
welcome

**Comment by takaaptech** [comment]
@liangxieq I update and test the new feature, It performs is very good with awesome Fade in-out effect
Thank so much!
I think we should have entry function to animate components in the Panel. For example, when we transition from UIMenuPanel To UISectionPanel, we should have Button Play on UIMenuPanel fade out and move by InCubic and "Button Back" in UISectionPanel fade in and move with OutCubic for example.
Thanks!

**Comment by liangxieq** [comment]
get it thx! @takaaptech

**Comment by liangxieq** [comment]
@takaaptech  hi, i've tried lots of solution. I find [this solution is most proper one](https://github.com/mob-sakai/UITransition). then i'll integrate it to  qframework.

**Comment by takaaptech** [comment]
@liangxieq Very nice! I have some time play with that plugin in the past
https://github.com/mob-sakai/UITransition/issues/14
He develops UISystem too: https://github.com/mob-sakai/UISystem/tree/develop
You have the right choice. It would be great because we have UISystem already!

**Comment by liangxieq** [comment]
cool! it's fate!

**Comment by liangxieq** [comment]
@takaaptech ahh ok. so sorry. I'll update before next month.
