### ISSUE TITLE
请问框架中，为什么不把UIMgr、UIManger合并呢，感觉使用中会带来困惑？

### ISSUE THREAD

**Issue by ilvxna** [liangxiegame/QFramework#38]
如题

**Comment by liangxieq** [comment]
UIMgr 里都是比较常用的 API 了，用起来比较爽快。 UIManager 是具体干活的，逻辑管理什么的都在这里搞定，其实 UIManager 的访问权限应该搞成 Internal。不过历史原因，还是有一定的人在用这个 API 了，所以现在在一个过渡阶段。

文档上都是建议使用 UIMgr 了。
