### ISSUE TITLE
感觉事件注册和触发可以直接放一起

### ISSUE THREAD

**Issue by ETRick** [liangxiegame/QFramework#4]
这里定义了事件接收和触发的接口，但扩展接口的类并没有实现接口中的方法，而是做了静态方法扩展，做成了类似多继承的形式，如果直接取消掉这两个接口，把事件注册和触发的方法放到一个单例类来实现是不是更优雅一些。

**Comment by ETRick** [comment]
“删除List需要从后向前遍历"，可以使用LinkedList就没有这个问题了。

**Comment by liangxiegame** [comment]
是的 要取消掉静态方法扩展的方式了,LinkedList这个谢谢了。

**Comment by ETRick** [comment]
:grin:
