### ISSUE TITLE
请问，有没有详细的roadmap？

### ISSUE THREAD

**Issue by ilvxna** [liangxiegame/QFramework#40]
如题，除了（http://qframework.io/RoadMap.html）这儿介绍的roadmap，有没有详细的roadmap规划。在做项目的过程中积累了不少组件，希望能够贡献代码。PS：希望加上多语言组件。以上

**Comment by liangxieq** [comment]
不好意思 roadmap 没及时更新，不过如果感兴趣可以加个 qq 或者微信: 441881077。
