### ISSUE TITLE
Best Practice for Sound And Music when using with QFramework

### ISSUE THREAD

**Issue by takaaptech** [liangxiegame/QFramework#43]
Hi @liangxiegame 
I have 2 music files and 10 mini sound files
Would you please take some note on API how to call Music and Sound in QFramework?
And what is the best practice for import setting (Preload audio check, Asset Bundle or not ), What is the folder position (Resources or ArtRes) should I save the sound and music?
Thank so much!

**Comment by Bian-Sh** [comment]
at which platform ,standalone(PC)?

**Comment by liangxieq** [comment]
U can save sound and music in any of Assets forlder.
