### ISSUE TITLE
Unity 2018.2: `UnityEngine.Network' is obsolete

### ISSUE THREAD

**Issue by ttdamowang** [liangxiegame/QFramework#45]
`error CS0619: 'Network' is obsolete: 'The legacy networking system has been removed in Unity 2018.2. Use Unity Multiplayer and NetworkIdentity instead.'`

**Comment by webloverand** [comment]
Hi,
We have updated a version to solve this problem,
You can download and use it again : https://github.com/liangxiegame/QFramework/releases
