### ISSUE TITLE
EditorToolKit v0.2.0报错

### ISSUE THREAD

**Issue by ChanWunsam** [liangxiegame/QFramework#46]
新版本EditorToolKit会导致从App入口(TodoList教程里的主入口)开启时,报出一堆错误.

主要报错信息如下:

NullReferenceException: Object reference not set to an instance of an object
QFramework.TransformInspector.OnEnable () (at Assets/QFramework/Framework/3.EditorToolKit/Editor/Inspectors/TransformInspector.cs:90)

**Comment by liangxieq** [comment]
谢谢提醒，已经 fix 了
