### ISSUE TITLE
基于 UIRoot 的一个潜在 bug

### ISSUE THREAD

**Issue by ChanWunsam** [liangxiegame/QFramework#47]
## 描述
使用QF插件的UIRoot组件时，会在开始时将Design下所有组件Inactivate，然后通常在Common下重新生成。
这里使用上容易产生一个bug：某一个组件在Awake()阶段进行初始化变量，通常没什么问题；如果在Awake()阶段委托事件，或者轮询，会在短时间内重复调用两次。

## 重现
这里我贴上代码和Log信息：
``` 代码
public partial class XXX : UIElement
{
private void Awake()
{
    Debug.Log("Awake()" + Time.realtimeSinceStartup);
}
}
```
``` Log
Awake()9.370213
Awake()10.41701
```

## 建议
为防止新手使用的时候出现相同bug不知所措，建议如下：
1. 生成文件时去掉Awake()，并在文档中建议不要使用，直接自定义一个Init()；
2. 或者UIRoot将Design下的组件全部Delete而不是Inactivate，并取消所有委托事件。

**Comment by ChanWunsam** [comment]
上面的建议1取消。一些较为独立的模块，通过自定义Init()唤醒实在太麻烦了，用Awake()会很方便。但使用时需注意本问题所提到的一些bug。

**Comment by liangxieq** [comment]
这是不推荐使用的方式， Design 是用来在设计阶段用的，也就是拼界面和做一些布局工作的使用用的。正式发布和跑项目的时候的界面全部都是动态加载的。
