### ISSUE TITLE
CollectedPSHP是一个挂载到mono的类，请问我的用法哪里有问题为啥对象池生不出来

### ISSUE THREAD

**Issue by a405457747** [liangxiegame/QFramework#48]

**Comment by a405457747** [comment]
public class PSHpAboutObjectPool : MonoSingleton<SliderParent>
{
    SimpleObjectPool<CollectedPSHP> hpObjectPool;

    private void Start()
    {
        hpObjectPool = new SimpleObjectPool<CollectedPSHP>(() => new CollectedPSHP(), HpReset, 10);
        print(hpObjectPool.CurCount);
    }

    private void HpReset(CollectedPSHP obj)
    {
        obj.Recycle();
    }

    private void Update()
    {
        if (Input.GetKeyDown(KeyCode.W))
        {
            //下面fishOne为Null
            CollectedPSHP fishOne = hpObjectPool.Allocate();
            GameObject fishOneObj = GameObject.Instantiate(fishOne.gameObject, transform.position, Quaternion.identity) as GameObject;
            print(fishOneObj.name);
        }
    }
}

**Comment by liangxieq** [comment]
CollectedPSHP 需要挂到一个 GameObject 上才可以。
