### ISSUE TITLE
无法在Unity 2018.3.11f1下编译通过，ArrayPool的Shared只在NET STANDARD下有

### ISSUE THREAD

**Issue by ymilv** [liangxiegame/QFramework#49]
0.19版，安装后发现无法启动Qframework，报错：Assets\QFramework\Framework\0.Core\Plugins\UniRx\Async\Triggers\AsyncTriggerBase.cs(194,84): error CS0117: 'ArrayPool<CancellationTokenRegistration>' does not contain a definition for 'Shared'
查了一下MSDN，NetFrameWork中ArrayPool类没有Shared，只在Net Standard中有。
项目设置中编译目标是NET STANDARD_2_0，把编译器从Mono改为IL2CPP依然不行。

**Comment by liangxieq** [comment]
这个只要自行更新UniRx 就可以了
