### ISSUE TITLE
请教下消息机制问题

### ISSUE THREAD

**Issue by voq** [liangxiegame/QFramework#5]
你的框架中实现了两种消息机制
1.以QMsgCenter派发给各个Manager。
2.以接口IMsgReceiver，IMsgSender实现的消息传递。

问题：
1.这两种的各自用途都在哪？
2.以及用第2种替换第1种进行manager之间的消息传递会有什么问题（劣势，不足）。

最好能举例说明下，先谢谢了。

**Comment by liangxieq** [comment]
1.QMsgCenter的消息id书enum类型
2.IMsgSender底层是用QMsgDispatcher实现的消息Id是string类型

第一种效率高，第二种效率低，速度是三倍左右。

**Comment by liangxieq** [comment]
局部消息相对于全局消息更安全，更方便调试。
