### ISSUE TITLE
中文乱码问题

### ISSUE THREAD

**Issue by YuanJingzhe** [liangxiegame/QFramework#55]
自动生成的UI Code文件默认编码为GB2312，打开UI界面如果有参数，输出的中文字符串会乱码，需手动改为UTF-8编码格式。如果自动创建的代码文件默认是UTF-8，就完美了

**Comment by liangxieq** [comment]
嗯嗯 谢谢建议 近期会尽快改善

**Comment by cornm1** [comment]
路径：
\Assets\QFramework\Framework\3.UIKit\0.CodeGen\Editor\CodeGen\CompilingSystem.cs
更改：
//File.WriteAllText(fileInfo.FullName, codeFileGenerator.ToString());
File.WriteAllText(fileInfo.FullName, codeFileGenerator.ToString(), Encoding.UTF8);

生成的文件就是UTF8了

**Comment by liangxieq** [comment]
谢谢提供，已经发布了 v0.10.21 版本
