### ISSUE TITLE
有计划支持lua吗？

### ISSUE THREAD

**Issue by hanyu363** [liangxiegame/QFramework#6]
有计划支持lua吗？
slua?
tolua?
xlua?

**Comment by liangxieq** [comment]
有的已经slua和tolua,结构正在整理

**Comment by hanyu363** [comment]
现在主流的slua和tolua还有新开源的xlua，选择哪个来当做框架的lua脚本支持呢？

**Comment by liangxieq** [comment]
slua已经在公司的项目使用过,tolua也做了几个项目。目前先支持这两种，最后花时间弄xlua。

**Comment by liangxieq** [comment]
支持tolua和slua的版本的API还没有完全稳定下来，稳定下来之后会发布。
