### ISSUE TITLE
UIkit创建UI脚本，unity闪退，脚本创建失败

### ISSUE THREAD

**Issue by YDC923092666** [liangxiegame/QFramework#61]
![image](https://user-images.githubusercontent.com/24561571/62423653-bddb0100-b6f5-11e9-9f04-4b768ec90743.png)
UI KIT 版本V0.5.2
 /../../Scripts/UI   最后面加上一个/，会导致unity闪退，生成文件失败。但是如果不加/，UI文件不会生成在指定的UI文件夹下，而是在UI文件夹同一级。

**Comment by liangxieq** [comment]
需要在 Assets 目录下，建议更新到最新版本。
