### ISSUE TITLE
QF框架的缓存要怎么清除？

### ISSUE THREAD

**Issue by NoxLeviathan** [liangxiegame/QFramework#67]
我的项目使用了QF框架，其中生成了一个预制体，但没有实例化出来到场景中，因为只需要使用它身上的一些提前设置好的属性。
今天发现了这个问题：当我勾选模拟模式的时候，我对该预制体进行的一切操作都无法生效，或者说，我必须把它实例化到场景中生成的才是正确的预制体，若不生成在场景中，则是之前的老旧版本的预制体。
即我添加Instantiate(LoadSync<GameObject>("prefabPath"))时生成出来的预制体是正确的，但我直接LoadSync<GameObject>("prefabPath")时生成的则是旧版本的预制体，而非当前版本的预制体。

取消勾选模拟模式时该BUG消失。
清除掉所有的AB包，重新生成AB也无法解决该BUG。

**Comment by liangxieq** [comment]
这个应该不是 QF 的问题，prefab 本来就不支持这么使用的。
