### ISSUE TITLE
更新版本出现Action和System.Action冲突的情况

### ISSUE THREAD

**Issue by SteveYung-tech** [liangxiegame/QFramework#68]
更新版本出现Action和System.Action冲突的情况，我不得已改了QFramework的Action 的名字，因为我项目中用到原生的Action的地方太多了，不知道有没有别的方法？

**Comment by liangxieq** [comment]
我今晚再发一个版本吧  我把 Action 重命名为 NodeAction 或者 其他比较合适的名字，如果你有比较好的名字推荐可以告诉我。

**Comment by liangxieq** [comment]
改成  ActionKitAction 如何？ 已经发布一个版本了。
