### ISSUE TITLE
更新的新版本UI层级出现点击屏蔽问题

### ISSUE THREAD

**Issue by SteveYung-tech** [liangxiegame/QFramework#69]
后面展示的页面被下层的UI的点击事件拦截，这个看了很久没搞明白什么原因，反正我是看到原来的分层改成了Canvas来控制，以前好好的，然后更新了就出现了，我退回去原来的版本了，总的来说问题太多，可能没用到项目里面验证吧。

**Comment by SteveYung-tech** [comment]
退回来问题消失

**Comment by liangxieq** [comment]
新版的 UI 用的是一个 Panel 对应一个 Canvas，这样性能更好一些，有 UI 事件要处理的 Panel 要挂上一个 Graphic Raycaster 就好了。

> 2020年11月6日 下午4:37，SteveYung-tech <notifications@github.com> 写道：
> 
> 后面展示的页面被下层的UI的点击事件拦截，这个看了很久没搞明白什么原因，反正我是看到原来的分层改成了Canvas来控制，以前好好的，然后更新了就出现了，我退回去原来的版本了，总的来说问题太多，可能没用到项目里面验证吧。
> 
>

**Comment by SteveYung-tech** [comment]
> 新版的 UI 用的是一个 Panel 对应一个 Canvas，这样性能更好一些，有 UI 事件要处理的 Panel 要挂上一个 Graphic Raycaster 就好了。
> […](#)
> 2020年11月6日 下午4:37，SteveYung-tech ***@***.***> 写道： 后面展示的页面被下层的UI的点击事件拦截，这个看了很久没搞明白什么原因，反正我是看到原来的分层改成了Canvas来控制，以前好好的，然后更新了就出现了，我退回去原来的版本了，总的来说问题太多，可能没用到项目里面验证吧。

这个肯定是有Graphic Raycaster的，每个panel都有这个，但是有一些上层的panel就是点击事件会穿透到下面去，找不到原因，都是差不多的panel

**Comment by liangxieq** [comment]
这个问题解决了吗？
