### ISSUE TITLE
AddTo方法找不到

### ISSUE THREAD

**Issue by SteveYung-tech** [liangxiegame/QFramework#70]
![image](https://user-images.githubusercontent.com/66808873/99240128-00ffab80-2837-11eb-8601-7773f47e0cdc.png)

**Comment by SteveYung-tech** [comment]
Unity版本 2019.4.8f1

**Comment by SteveYung-tech** [comment]
使用Package Kit重新倒入解决

**Comment by liangxieq** [comment]
童鞋，方便加个 QQ 吗 441881077
