### ISSUE TITLE
报错，以下是所有报错所以不知道是什么引起的，但是是在更新了新版本之后出现的

### ISSUE THREAD

**Issue by SteveYung-tech** [liangxiegame/QFramework#71]
Trying to add Fill (UnityEngine.UI.Image) for graphic rebuild while we are already inside a graphic rebuild loop. This is not supported.
UnityEngine.UI.ScrollRect:LateUpdate() (at /Applications/Unity/Hub/Editor/2019.4.8f1/Unity.app/Contents/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/ScrollRect.cs:805)

**Comment by liangxieq** [comment]
这个报错和 QFramework 没关系
