### ISSUE TITLE
qf的uikit问题  : 自动创建uiroot

### ISSUE THREAD

**Issue by zlygithub-98** [liangxiegame/QFramework#73]
场景里明明存在一个uiroot，我使用UIKit.OpenPanel<某某Panel>();然后有的时候正常使用我的uiroot，还有时候场景中多了一个dontdestoryonload的uiroot 怎么才能让他用我的 而不是使用的创建新的uiroot?

**Comment by liangxieq** [comment]
这个可能是个 bug ，我检查下。

**Comment by liangxieq** [comment]
问下你的 QFramework 版本是多少?

**Comment by liangxieq** [comment]
我这边测试了一下，下来是没有这个问题的。
