### ISSUE TITLE
凉鞋老师好，最近在learn.u3d上学了你的框架课程有个疑问想问问你

### ISSUE THREAD

**Issue by bournes** [liangxiegame/QFramework#74]
很想知道如果要接入JEngine这类的热更新框架，需要做些什么，如果能出个视频教程吗？

**Comment by liangxieq** [comment]
可以在热更层面实现一遍 我记得 JEngine 是支持 ILRuntime 的，我在文章中介绍的代码在 ILRuntime 是完全支持的
