### ISSUE TITLE
ResKIt

### ISSUE THREAD

**Issue by USuperMe** [liangxiegame/QFramework#75]
AddressableAssetSystem Support,可以添加官方自己的AddressableAssetSystem  AssetBundle加载支持吗

**Comment by liangxieq** [comment]
可以支持

**Comment by USuperMe** [comment]
> 可以支持

鞋大，其实我的意思是能不能把整套框架内的ResKIt替换成AddressableAssetSystem或添加支持，因为官方的那套系统确实是很好用。。。本来打算看看框架源代码自己替换实现的，却发现对框架理解不深的话，替换起来寸步难行。

**Comment by liangxieq** [comment]
这里有文档：https://qframework.cn/qf/doc/detail/3ce37aa9-8434-4388-9e0c-4e97288683bd

**Comment by liangxieq** [comment]
先看文档 再看源码
