### ISSUE TITLE
讨论下收集节点的实现方式

### ISSUE THREAD

**Issue by lizijie** [liangxiegame/QFramework#8]
第一种：就像QFramework.QUIBehaviour.FindAllCanHandleWidget。以一个标记（QUIMark），判断是否缓存节点。使用时从中取出并GetComponent<T>。

```
void FindAllCanHandleWidget(Transform trans)
{
	for (int i = 0; i < trans.childCount; i++)
	{
		Transform childTrans = trans.GetChild(i);
		QUIMark uiMark = childTrans.GetComponent<QUIMark>();
		if (null != uiMark)
		{
			if (mUIComponentsDic.ContainsKey(childTrans.name))
			{
				Debug.LogError("Repeat Id: " + childTrans.name);
			}
			else
			{
				mUIComponentsDic.Add(childTrans.name, childTrans);
			}
		}
		FindAllCanHandleWidget(childTrans);
	}
}
```

第二种：其实就是Unity提供的、最原始的获取节点方法。
```
this.transform.Find("XXX/XXXX").gameObject.GetComponent<T>();
```

第一种方法的优势：
1. 不需要记住节点路径。
2. 在制作UI Prefab，即可视化地在Inspector窗口定义好哪个节点（QUIMask）需要在业务逻辑里用到
PS:优势还有补充么？

我刚入行Unity时，接触到的是第1种做法。后来接触其它项目，和同行了解到后。
偏向使用第二种做法，同时使用工具，硬编码生成，找到节点，UI事件注册（就像QFramewrok那样）、节点命名（需要业务逻辑使用的节点特殊前缀命名、即QUIMash的作用），来弥补第一种做法的优势。

**Comment by liangxieq** [comment]
未来会使用第二种方式实现的,thx
