### ISSUE TITLE
OpenPanel时，UIKitConfig 65行，Transform转换为RectTransform时失败，返回了null

### ISSUE THREAD

**Issue by AkiYama-Ryou** [liangxiegame/QFramework#83]
Panel是一个包含三层canvas的预制件。
我在66行加了if（panelRectTrans）的判断，不报错了但是不知道合不合适。

**Comment by AkiYama-Ryou** [comment]
无法把普通的Transform转换成rect transform

**Comment by liangxieq** [comment]
如果没出错就应该没问题

我也会把修改改到 UIKit 里，感谢提供。
