### ISSUE TITLE
ViewControllerCode.89行附近，GENERATE_NAMESPACE取值错误

### ISSUE THREAD

**Issue by AkiYama-Ryou** [liangxiegame/QFramework#84]
原本的逻辑应该是从viewcontroller的编辑器上取命名空间，如果指定了命名空间则使用，未指定则默认使用示例命名空间。
但是那个判断会犹豫未知原因出问题，即使指定了值，也依然会把GENERATE_NAMESPACE设置为示例空间。
导致如果更改了命名空间，生成代码时会报错。

**Comment by liangxieq** [comment]
这个问题应该最新版本解决掉了。
