### ISSUE TITLE
ViewController Inspector.cs 中79行附近，mCodeGenerateInfo在某种情况下取不到

### ISSUE THREAD

**Issue by AkiYama-Ryou** [liangxiegame/QFramework#85]
74行附近的target是null
一开始还挺正常的，在我删除了设置错误的viewcontroller后，亦或是在我修改了UI脚本生成路径后，编辑器开始不停报这里取不到值的错。因为是Editor问题不影响游戏，我在这里加了一行
if(!mCodeGenerateInfo) return;
但是具体的问题根源还是不明。

**Comment by liangxieq** [comment]
最近新版 应该解决掉了
