### ISSUE TITLE
建议考虑推出一个upm版本的放在openupm上面?

### ISSUE THREAD

**Issue by Aimoux** [liangxiegame/QFramework#88]
作为插件升级管理都会很方便

**Comment by liangxieq** [comment]
UPM 不支持 Unity 2018，而 QFramework 最低兼容到 Unity 2018 ，所以支持 UPM 每次发版本会比较麻烦，我个人时间精力比较有限。

不过后边等 QF 最低兼容升到 Unity 2019 的时候，也许会用 UPM 作为主要的版本发布手段，感谢建议。
