### ISSUE TITLE
更新Framework到v1.0.2版本报错

### ISSUE THREAD

**Issue by qgqceo** [liangxiegame/QFramework#92]
从插件管理面板更新Framework到v1.0.2版本报错。如下所示：
Assets/Script/Framework/QFramework/Toolkits/AudioKit/Scripts/Timer/Timer.cs(12,6): error CS1614: 'MonoSingletonPath' is ambiguous between 'MonoSingletonPath' and 'MonoSingletonPathAttribute'; use either '@MonoSingletonPath' or 'MonoSingletonPathAttribute'

**Comment by liangxieq** [comment]
如果是从 v0.14 以前的版本更新 会有一些错误，因为之前升级的机制有一个 bug，大概在 v0.15  修好了，从 v0.14 版本更新的话需要 删除掉 QFramework/Framework  和 QFramework/Toolkits 目录 然后重新导入下最新版。
