### ISSUE TITLE
WebGL

### ISSUE THREAD

**Issue by TastSong** [liangxiegame/QFramework#95]
WebGL平台下不能使用Q Framework

**Comment by liangxieq** [comment]
更新一下最新版的 QFramework.cs，旧版本确实有一些 bug。

**Comment by TastSong** [comment]
好的，我试一下

**Comment by TastSong** [comment]
![image](https://user-images.githubusercontent.com/32432306/183331453-7e642bb9-e159-4859-9ef6-10b83b58ffd0.png)
我用现在QFramework，然后打包测试场景“点点点”，也是不行，我用的Unity版本是2021.3.1

**Comment by liangxieq** [comment]
这个是 Unity 的问题，WebGL 需要这么选，如图所示
![image](https://user-images.githubusercontent.com/24365011/185741589-ec9d1338-bfef-46a5-a1dc-ac7801b77254.png)

Publish Settings 的 Compression Format 需要改成 Disabled 

否则就得用特殊的方式部署服务器上。
