### ISSUE TITLE
ActionKit.Repeat在放回缓存池时并没有清空mActions

### ISSUE THREAD

**Issue by thomaskjh** [liangxiegame/QFramework#97]
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/3124753/184056408-13126129-a813-45be-832e-618ff8f4701d.png">
对比Sequece和Repeat的Deinit方法，发现Repeat覆盖Deinit方法后，并没有将mSequence的mActions清空，导致重新回到缓存池里的Repeat在下一次分配时，依然存在上一次的mActions

**Comment by thomaskjh** [comment]
<img width="758" alt="image" src="https://user-images.githubusercontent.com/3124753/184057606-0b3ae6ed-de05-40c1-9a5e-31c7c70c4e27.png">
这两部分代码的顺序有问题  哈

**Comment by liangxieq** [comment]
好的，谢谢反馈，会在下个版本修复掉。

**Comment by liangxieq** [comment]
已在 v1.0.8 版本修复，感谢提供。
